"use client";
import React from "react";
const AV=[{bg:"#2a1f45",text:"#bf94ff"},{bg:"#0d2e1e",text:"#5af29b"},{bg:"#2e1a00",text:"#ffc74d"},{bg:"#0d1f2e",text:"#67b8f5"},{bg:"#2e0d1a",text:"#f59bbb"}];
export function avColor(s:string){const i=(s.charCodeAt(0)+(s.charCodeAt(1)||0))%AV.length;return AV[i];}
export function Avatar({initials,size=36}:{initials:string;size?:number}){const c=avColor(initials);return(<div style={{width:size,height:size,borderRadius:"50%",background:c.bg,color:c.text,display:"flex",alignItems:"center",justifyContent:"center",fontSize:size*0.35,fontWeight:500,flexShrink:0,border:`1px solid ${c.text}33`}}>{initials}</div>);}
export function Badge({children,type="default"}:{children:React.ReactNode;type?:string}){const s:any={default:{bg:"var(--bg3)",color:"var(--text1)"},green:{bg:"var(--green-dim)",color:"var(--green-text)"},amber:{bg:"var(--amber-dim)",color:"var(--amber-text)"},red:{bg:"var(--red-dim)",color:"var(--red-text)"},purple:{bg:"var(--purple-dim)",color:"var(--purple-text)"}}[type]||{bg:"var(--bg3)",color:"var(--text1)"};return(<span style={{background:s.bg,color:s.color,fontSize:11,padding:"3px 9px",borderRadius:20,fontWeight:500,whiteSpace:"nowrap"}}>{children}</span>);}
export function Btn({children,onClick,primary,small,disabled,full,style={}}:{children:React.ReactNode;onClick?:()=>void;primary?:boolean;small?:boolean;disabled?:boolean;full?:boolean;style?:React.CSSProperties}){return(<button onClick={onClick} disabled={disabled} style={{fontSize:small?12:14,padding:small?"6px 12px":"9px 16px",borderRadius:9,border:primary?"none":"1px solid var(--border-mid)",background:primary?"var(--purple)":"var(--bg3)",color:primary?"#fff":"var(--text0)",opacity:disabled?0.4:1,cursor:disabled?"not-allowed":"pointer",width:full?"100%":undefined,fontWeight:primary?500:400,...style}}>{children}</button>);}
export function ProgressBar({value}:{value:number}){return(<div style={{height:4,background:"var(--bg4)",borderRadius:2,overflow:"hidden",margin:"7px 0 11px"}}><div style={{height:"100%",width:`${value}%`,background:"var(--purple)",borderRadius:2}}/></div>);}
export function MetricCard({label,value,sub}:{label:string;value:string;sub?:string}){return(<div style={{background:"var(--bg2)",borderRadius:10,padding:"14px 16px",border:"1px solid var(--border)"}}><div style={{fontSize:10,color:"var(--text2)",marginBottom:6,textTransform:"uppercase",letterSpacing:"0.07em"}}>{label}</div><div style={{fontSize:20,fontWeight:600,color:"var(--text0)"}}>{value}</div>{sub&&<div style={{fontSize:11,color:"var(--text2)",marginTop:3}}>{sub}</div>}</div>);}
export function fmtViews(n:number):string{if(n>=1000000)return(n/1000000).toFixed(1)+"M";if(n>=1000)return Math.round(n/1000)+"K";return n.toString();}
export function fmtMoney(n:number):string{return"$"+n.toFixed(2);}
export function pct(a:number,b:number):number{return b===0?0:Math.min(100,Math.round((a/b)*100));}
